wybory/urls.py
from django.conf.urls import url
from django.contrib import admin

from wyboryApp import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

for url in urls.urls:
    urlpatterns.append(url)

wyboryApp/urls.py
from django.conf.urls import url

from . import views

urls = [
    url(r'^kandydaci', views.KandydatView.as_view()),
    url(r'^$', views.main_page),
    url(r'^login', views.user_login),
    url(r'^logout', views.user_logout),
    url(r'^index', views.index),
    url(r'^woj/(?P<name>.+)', views.woj),
    url(r'^okr/(?P<num>[0-9]+)', views.okr),
    url(r'^gmina/(?P<nazwa>.+?)-(?P<id>[0-9]+)', views.gmina),
    url(r'^edit/(?P<obwod_id>[0-9]+)/(?P<candidate_id>[0-9]+)', views.edit_view),
    url(r'^search', views.search),
]

wyboryApp/models.py
from django.db import models

# Create your models here.

class Kandydat(models.Model):
    imie = models.CharField(max_length=42)
    nazwisko = models.CharField(max_length=42)

    def __str__(self):
        return "{} {}".format(self.imie, self.nazwisko)

    class Meta:
        unique_together = ("imie", "nazwisko")
        verbose_name_plural = "Kandydaci"

class Okreg(models.Model):
    numer = models.IntegerField(unique=True)
    gminy = models.ManyToManyField("Gmina", through="Obwod")

    def __str__(self):
        return "Okręg nr. {}".format(self.numer)
    
    class Meta:
        verbose_name_plural = "Okręgi"

class Gmina(models.Model):
    nazwa = models.CharField(max_length=64)
    okregi = models.ManyToManyField("Okreg", through="Obwod")

    def __str__(self):
        return "{}".format(self.nazwa)
    
    class Meta:
        verbose_name_plural = "Gminy"

class Obwod(models.Model):
    gmina = models.ForeignKey("Gmina")
    okreg = models.ForeignKey("Okreg")
    uprawnieni = models.IntegerField()
    wydane = models.IntegerField()
    niewazne = models.IntegerField()

    def __str__(self):
        return "Obwód nr. {}".format(self.id)

    class Meta:
        verbose_name_plural = "Obwody"

class Wynik(models.Model):
    kandydat = models.ForeignKey("Kandydat")
    obwod = models.ForeignKey("Obwod")
    glosy = models.IntegerField()

    class Meta:
        unique_together = ("kandydat", "obwod")

wyboryApp/views.py
from json import loads

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views import View
from django.db.models import Sum
from django.views.generic import ListView
from django.contrib.auth import authenticate, logout, login
from django import forms
from django.db import transaction, IntegrityError

from django.middleware import csrf

from . import models
from .logic import get_stats, get_candidates, integrity_check

from django.db.models import Model
from django.db.models.query import QuerySet
from django.forms import model_to_dict

def good_to_go(o):
    if hasattr(o, 'to_dict'):
        return o.to_dict()
    elif issubclass(o.__class__, Model):
        if hasattr(o, '__str__'):
            return o.__str__()
        return model_to_dict(o)
    elif issubclass(o.__class__, QuerySet) or isinstance(o, list):
        return [good_to_go(m) for m in o]
    elif isinstance(o, dict):
        return {k: good_to_go(v) for k, v in o.items()}
    else:
        return o

WOJEWODZTWO_OKREGI = {
    "dolnośląskie": (1, 2, 3, 4),
    "kujawsko-pomorskie": (5, 6, 7),
    "lubelskie": (8, 9, 10, 11, 12),
    "lubuskie": (13, 14),
    "łódzkie": (15, 16, 17, 18, 19),
    "małopolskie": (20, 21, 22, 23, 24, 25, 26, 27),
    "mazowieckie": (28, 29, 30, 31, 32, 33, 34, 35, 36),
    "opolskie": (37, 38),
    "podkarpackie": (39, 40, 41, 42),
    "podlaskie": (43, 44, 45),
    "pomorskie": (46, 47, 48),
    "śląskie": (49, 50, 51, 52, 53, 54),
    "świętokrzyskie": (55, 56),
    "warmińsko-mazurskie": (57, 58, 59),
    "wielkopolskie": (60, 61, 62, 63, 64),
    "zachodniopomorskie": (65, 66, 67, 68)
}


class KandydatView(ListView):
    model = models.Kandydat

    template_name = "kandydat.html"


class KandydatForm(forms.Form):
    imie = forms.CharField(label="Imię")
    nazwisko = forms.CharField(label="Nazwisko")

    def clean(self):
        if self.cleaned_data.get("nazwisko") in ("Nowak", "Kowalski"):
            self.add_error("nazwisko", "Nie chcemy tych panów!")


def szukaj_kandydat(request):
    if request.method == "POST":
        form = KandydatForm(request.POST)
        if form.is_valid():
            return HttpResponse("Kandydat: {} {}".format(form.imie, form.nazwisko))
        else:
            return HttpResponse(form.nazwisko.error_messages)


class LoginForm(forms.Form):
    user = forms.CharField(label="Login")
    password = forms.CharField(widget=forms.PasswordInput)


def user_login(request):
    if request.method == "GET":
        csrf.get_token(request)        
        return render(request, "login.html", {"form": LoginForm()})
    elif request.method == "POST":
        form = LoginForm(request.POST)
        form.is_valid()
        user = authenticate(username=form.cleaned_data["user"], password=form.cleaned_data["password"])
        if user is None:
            result = JsonResponse({"error": "Invalid login or password."})
            result.status_code = 420
            return result
        else:
            login(request, user)
            return JsonResponse({"auth":True})


def user_logout(request):
    logout(request)
    return JsonResponse({"auth":False})

def context(request, data, more):
    stats = get_stats(data)

    kandydaci = get_candidates(stats)

    stats.pop("obwody", None)
    return {
        "auth": True if request.user.is_authenticated else False,
        "stats": stats,
        "mainResult": kandydaci,
        "more": more,
        "currUrl": request.path,
    }
def view(request, data, template, more=None):
    _context = context(request, data, more)

    return render(request, template, _context)

def json(request, data, type, more=None):
    _context = good_to_go(context(request, data, more))
    _context["type"] = type
    return JsonResponse(_context, safe=False)

def main_page(request):
    csrf.get_token(request) #so that a new user can submit login form
    return view(request, models.Obwod.objects.filter(id__lt=0), "index.html")

def index(request):
    return json(request, models.Obwod.objects.all(), "main")

def woj(request, name):
    okregi = list(WOJEWODZTWO_OKREGI[name])
    data = models.Obwod.objects.filter(okreg__numer__in=okregi)
    if not list(data):
        return HttpResponseRedirect("/")
    return json(request, data, "details",
                {"links":
                 [{"url": "/okr/{}".format(x), "nazwa": "Okręg Nr {}".format(x)}
                  for x in okregi]
                })


def okr(request, num):
    data = models.Obwod.objects.filter(okreg__numer__in=[num])
    if not list(data):
        return HttpResponseRedirect("/")
    return json(request, data, "details",
                {"links":
                 [{"url": "/gmina/{}-{}".format(x.nazwa, x.id), "nazwa": "{}".format(
                     x.nazwa)} for x in models.Okreg.objects.get(numer=num).gmina_set.distinct()]
                })

def gmina(request, nazwa, id):
    data = models.Obwod.objects.filter(gmina__id=id)
    if not list(data):
        return HttpResponseRedirect("/")
    return json(request, data, "gmina",
                {"results":
                 [{"id": x.id, "result": get_candidates(get_stats(data.filter(
                     id=x.id))), "max": get_stats(data.filter(
                     id=x.id))["wydane"] - get_stats(data.filter(
                     id=x.id))["niewazne"], "miejsce": "w obwodzie nr {}".format(x.id)} for x in data]
                })


class EditForm(forms.Form):
    oddane = forms.IntegerField()
    
    def clean(self):
        if self.cleaned_data.get("oddane") < 0:
            self.add_error("oddane", "Ujemna wartość!")


def edit_view(request, obwod_id, candidate_id):
    candidate = models.Kandydat.objects.get(id=candidate_id)
    wynik = models.Wynik.objects.filter(
        obwod__id=obwod_id).get(kandydat__id=candidate_id)

    success = None
    error = None

    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            oddane = form.cleaned_data["oddane"]
            try:
                with transaction.atomic():
                    wynik.glosy = oddane
                    wynik.save()
                    integrity_check(wynik)
                    success = "Zaktualizowano dane."
            except IntegrityError:
                error = "Liczba głosów oddanych w obwodzie nie może przekraczać liczby wydanych kart."
        else:
            error = "Błąd w przesłanych danych"
    else:
        form = EditForm(initial={"oddane": wynik.glosy})
        csrf.get_token(request)

    context = {
        "nazwa": "{} {}".format(candidate.imie, candidate.nazwisko),
        "obwod": obwod_id,
        "success": success,
        "error": error,
    }
    if "return" in request.GET:
        context["back"] = request.GET["return"]

    return JsonResponse(good_to_go(context))


def search(request):
    if "q" not in request.GET:
        return HttpResponseRedirect("/")

    phrase = request.GET["q"]
    gminy = models.Gmina.objects.filter(nazwa__contains=phrase)

    context = {
        "gminy": [{"nazwa": x.nazwa, "id": x.id} for x in gminy]
    }

    return JsonResponse(good_to_go(context), safe=False)

def json_to_dict(get_response):
    def middleware(request):
        body_unicode = request.body.decode('utf-8')
        if body_unicode.startswith("{"):
            request.POST = loads(body_unicode)
        response = get_response(request)
        return response
    return middleware

wyboryApp/templates/details.html
{% extends 'index.html' %}
{% block content %}
    <div class="flex-wrapper reverse-when-small">
        {% include 'results.html' %}
        {% include 'statistics.html' %}
    </div>
    <section id="more-wrapper">
        <h3>Wyniki szczegółowe</h3>
        <div id="more" class="flex-wrapper flex-left horizontal-space margin-auto col-2">
            {% for r in more.links %}
            <div class="col-3">
                <a href="{{ r.url }}">{{ r.nazwa }}</a>
            </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

wyboryApp/templates/edit.html
        {% if error %}<p style="color: red;">{{error}}</p>{% endif %}
        {% if success %}<p style="color: green;">{{success}}</p>{% endif %}
        <p>Wynik kandydata {{nazwa}} w obwodzie nr {{obwod}}</p>       
        <form action="{{currUrl}}?return={{back}}" method="post" id="edit-form">
            {% for field in form %}
                <div class="fieldWrapper">
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field }}
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <input type="submit" value="Submit" />
            {% if back %}<a href="{{back}}"><input type="button" value="Back" /></a>{% endif %}
        </form>

wyboryApp/templates/gmina.html
{% extends 'index.html' %}
{% block content %}
    <div class="flex-wrapper">
        {% include 'results.html' %}
        {% include 'statistics.html' %}
    </div>
    <div class="flex-wrapper">
    {% for obwód in more.details %}
        {% with kandydaci=obwód.kandydaci editId=obwód.id place=obwód.miejsce %}
        {% include 'results.html' %}
        {% endwith %}
    {% endfor %}
    </div>
{% endblock %}

wyboryApp/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Wybory Prezydenta Rzeczypospolitej Polskiej 2000">
    <title>Wybory Prezydenta Rzeczypospolitej Polskiej 2000</title>

    <link rel="stylesheet" type="text/css" href="{% static "style.css" %}">
</head>

<body>
    <header class="center-text">
        <div class="shrinkwrap">
            <a href="/index">
                <h1>Wybory Prezydenta Rzeczypospolitej Polskiej 2000</h1>
            </a>
        </div>
        <div>
            {% if auth == True %}
            <a href="#" id="logout">Logout</a> {% else %}
            <a href="#" id="login">Login</a> {% endif %}
            <a href="#" id="search_btn">Search</a>
            <!--<form method="get" action="/search">
                <input type="text" name="q">
                <input type="submit" value="Szukaj">
            </form>-->
        </div>
    </header>

    <main>
        {% block content %}
        <div class="flex-wrapper">
            {% include 'map.html' %} {% include 'statistics.html' %} {% include 'results.html' %}
        </div>

        <div id="results-wrapper" class="flex-wrapper">
        </div>
        <section id="more-wrapper" style="display: none">
            <h3>Wyniki szczegółowe</h3>
            <div id="more" class="flex-wrapper flex-left horizontal-space margin-auto col-2">
                {% for r in more.links %}
                <div class="col-3">
                    <a href="{{ r.url }}">{{ r.nazwa }}</a>
                </div>
                {% endfor %}
            </div>
        </section>
        {% endblock %}
    </main>
    <div class="dimmer" id="popup-wrapper">
        <div class="popup" id="popup">
            <a href="#" onclick="setVisibility('popup-wrapper', false); return false">[x] CLOSE</a>
            <div id="popup-login">
                <p style="color: red;" id="login-form-err"></p>
                <form action="/login" method="post" id="form-login">
                    <div class="fieldWrapper">
                        <label for="id_user">Login:</label> <input id="id_user" name="user" type="text" required>
                    </div>
                    <div class="fieldWrapper">
                        <label for="id_password">Password:</label>
                        <input id="id_password" name="password" type="password" required>
                    </div>
                    <input type="submit" value="Login" id="submit-login" />
                </form>
            </div>
            <div id="popup-search">
                <form id="search-form" onsubmit="return searchSubmit()">
                    <center><label>Szukaj</label></center><br/>
                    <input type="text" name="q">
                    <button type="submit">Szukaj</button>
                </form>
                <div id="search-results">
                </div>
            </div>
            <div id="popup-edit">
                <p style="color: red;" id="edit-form-err"></p>
                <p style="color: green;" id="edit-form-succ"></p>
                <p>Wynik kandydata <span id="edit-form-name"></span> w obwodzie nr <span id="edit-form-id"></span></p>
                <form id="edit-form">
                    <div class="fieldWrapper">
                        <label for="id_oddane">Oddane:</label>
                        <input id="id_oddane" name="oddane" value="" required="" type="number">
                    </div>
                    <input type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </div>
    <script src="{% static "site.js" %}"></script>
</body>

</html>

wyboryApp/templates/kandydat.html
<html>
    <body>
    <h2>Kandydaci</h2>
    <ul>
        {% for candidate in object_list %}
            <li>{{ candidate.imie }} {{ candidate.nazwisko }}</li>
        {% endfor %}
    </ul>
</body>
</html>

wyboryApp/templates/login.html
        {% if error %}<p style="color: red;">{{error}}</p>{% endif %}
        <form action="/login" method="post" id="form-login">
            
            {% for field in form %}
                <div class="fieldWrapper">
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field }}
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <input type="submit" value="Login" id="submit-login" />
        </form>

wyboryApp/templates/results.html
            <section id="mainResult" class="shrinkwrap">
                <h3>Wyniki wyborów</h3>
                <table>
                    <thead>
                        <tr>
                            <th>Imię i nazwisko</th>
                            <th>Liczba oddanych głosów</th>
                            <th>Wynik wyborczy (%)</th>
                            <th style="visibility: collapse;">Edycja</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for kandydat in mainResult %}
                        <tr>
                            <td>{{ kandydat.nazwa }}</td>
                            <td class="data-glosy">{{ kandydat.glosy }}</td>
                            <!--make bar from percent-->
                            <td>
                                <div class="flex-wrapper flex-between flex-small-right">
                                    <div class="votebar-wrapper">
                                        <div class="votebar" style="width:{{ kandydat.procent }}%;"></div>
                                    </div>
                                    <span>{{ kandydat.procent }}%</span>
                                </div>
                            </td>
                            <td style="visibility: collapse;"></td>
                <!--{% if auth %}{% if editId %}<td><a href="/edit/{{editId}}/{{kandydat.id}}?return={{currUrl}}">Edytuj</a></td>{% endif %}{% endif %} -->
                            
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </section>

wyboryApp/templates/search.html
<html>
    <body>
    <h2>Wyniki</h2>
    <ul>
        {% for gmina in gminy %}
            <li><a href="/gmina/{{gmina.nazwa}}-{{gmina.id}}">{{gmina.nazwa}}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

wyboryApp/templates/statistics.html
            <section>
                <div>
                    <h3>Zbiorcze statystyki głosowania</h3>
                    <table class="statystyki">
                        <tr>
                            <td>Liczba uprawnionych do głosowania</td>
                            <td id="stats.uprawnieni">{{ stats.uprawnieni }}</td>
                        </tr>
                        <tr>
                            <td>Liczba kart wydanych</td>
                            <td id="stats.wydane">{{ stats.wydane }}</td>
                        </tr>
                        <tr>
                            <td>Liczba głosów oddanych</td>
                            <td id="stats.oddane">{{ stats.oddane }}</td>
                        </tr>
                        <tr>
                            <td>Liczba głosów ważnych</td>
                            <td id="stats.wazne">{{ stats.wazne }}</td>
                        </tr>
                        <tr>
                            <td>Liczba głosów nieważnych</td>
                            <td id="stats.niewazne">{{ stats.niewazne }}</td>
                        </tr>
                        <tr>
                            <td>Frekwencja</td>
                            <td id="stats.frekwencja">{{ stats.frekwencja }}%</td>
                        </tr>
                    </table>
                </div>
            </section>